### ISSUE TITLE
Error en paso 2

### ISSUE THREAD

**Issue by isaioliva** [lalogsbaufest/challengeshoprus#2]
C:\testEVO\Eduardo\challengeshoprus-master\challengeshoprus-master\generics-microservicios>gradle -version

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Windows 10 10.0 amd64

C:\testEVO\Eduardo\challengeshoprus-master\challengeshoprus-master\generics-microservicios>gradlew.bat
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

**Comment by lalogsbaufest** [comment]
Se han agregado los gradle-wrapper.jar para no depender de la configuración del sistema, también se actualizo el README.md donde se explica la forma para construir y ejecutar los módulos. Favor de actualiza el proyecto y seguir la nueva lista de pasos.
